### ISSUE TITLE
Error while download 

### ISSUE THREAD

**Issue by ScoobyDooWaffle** [Nojus0/YouTube-Livestream-Archiver#1]
The remote server returned an error: (403) Forbidden.

**Comment by ScoobyDooWaffle** [comment]
It's from Trovo

**Comment by Nojus0** [comment]
Just tested it on RiotGames Trovo channel works fine found the live stream and am downloading it, is the platform for the trovo channel platform set to 1 in config, post your config here if you can.

**Comment by ScoobyDooWaffle** [comment]
I was on WaffleUncle channel

**Comment by ScoobyDooWaffle** [comment]
UCcJL2ld6kxy_nuV1u7PVQ0g

**Comment by ScoobyDooWaffle** [comment]
{
  "ChannelGroups": [
    {
      "Channels": [
        {
          "ChannelId": "waffleuncle",
          "MinutesTimeOut": 6,
          "Platform": 1
        }
      ],
      "Async": false,
      "AsyncMinuteDelay": 6
    }
  ]
}

**Comment by ScoobyDooWaffle** [comment]
I try on different channel same result with : drKiray

**Comment by Nojus0** [comment]
![image](https://user-images.githubusercontent.com/35661992/117698986-38cf2680-b1bc-11eb-861f-06c4912f35be.png)

Works for me, try to re-download the application, it's already precompiled both in debug and release. Or you can compile it yourself.

**Comment by ScoobyDooWaffle** [comment]
I dont have same result can you add me on discord

**Comment by ScoobyDooWaffle** [comment]
WaffleUncle#1850

**Comment by ScoobyDooWaffle** [comment]
Oh nerver mind

**Comment by ScoobyDooWaffle** [comment]
It's not downloading btw i think

**Comment by ScoobyDooWaffle** [comment]
![image](https://user-images.githubusercontent.com/76669896/117701299-10800180-b195-11eb-8b2b-4f9d96f4a550.png)

**Comment by Nojus0** [comment]
Check the livestreams folder for livestreams file.

**Comment by Nojus0** [comment]
Assumed to be fixed.
